/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.NhanVienPDT;

import java.awt.BorderLayout;
import views.DangNhap;
import views.MainView;

/**
 *
 * @author Admin
 */
public class HomeNhanVien extends javax.swing.JPanel {
        private static DangNhap dangNhap;
        private static MainView mainView;
    /**
     * Creates new form HomeNV
     */
    public HomeNhanVien(DangNhap dangNhap, MainView mainView) {
        initComponents();
        this.dangNhap = dangNhap;
        this.mainView = mainView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnThongTinCaNhan = new javax.swing.JButton();
        btnPhienDangKy = new javax.swing.JButton();
        btnGiangVien = new javax.swing.JButton();
        btnSinhVien = new javax.swing.JButton();
        btnLopTinChi = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnMonHoc = new javax.swing.JButton();

        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(980, 640));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sv.png"))); // NOI18N
        btnThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinCaNhanActionPerformed(evt);
            }
        });

        btnPhienDangKy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPhienDangKy.setText("Năm Học và Phiên");
        btnPhienDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhienDangKyActionPerformed(evt);
            }
        });

        btnGiangVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGiangVien.setText("Giảng Viên");
        btnGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiangVienActionPerformed(evt);
            }
        });

        btnSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSinhVien.setText("Sinh Viên");
        btnSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhVienActionPerformed(evt);
            }
        });

        btnLopTinChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLopTinChi.setText("Lớp Tín Chỉ");
        btnLopTinChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLopTinChiActionPerformed(evt);
            }
        });

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMonHoc.setText("Môn Học");
        btnMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(btnThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPhienDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGiangVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLopTinChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPhienDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGiangVien)
                .addGap(18, 18, 18)
                .addComponent(btnSinhVien)
                .addGap(18, 18, 18)
                .addComponent(btnLopTinChi)
                .addGap(18, 18, 18)
                .addComponent(btnMonHoc)
                .addGap(18, 18, 18)
                .addComponent(btnDangXuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinCaNhanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnThongTinCaNhanActionPerformed

    private void btnPhienDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhienDangKyActionPerformed
        // TODO add your handling code here:
        NamHocPhienView namHocPhienView = new NamHocPhienView();

        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(namHocPhienView);
        jPanel1.validate();
        jPanel1.repaint();
    }//GEN-LAST:event_btnPhienDangKyActionPerformed

    private void btnGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiangVienActionPerformed
        // TODO add your handling code here:
        GiangVienView giangVienView = new GiangVienView();

        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(giangVienView);
        jPanel1.validate();
        jPanel1.repaint();
    }//GEN-LAST:event_btnGiangVienActionPerformed

    private void btnSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhVienActionPerformed
        // TODO add your handling code here:
        SinhVienView sinhVienView = new SinhVienView();

        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(sinhVienView);
        jPanel1.validate();
        jPanel1.repaint();
    }//GEN-LAST:event_btnSinhVienActionPerformed

    private void btnLopTinChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLopTinChiActionPerformed
        // TODO add your handling code here:
        LopTinChiView lopTinChiView = new LopTinChiView();
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(lopTinChiView);
        jPanel1.validate();
        jPanel1.repaint();
    }//GEN-LAST:event_btnLopTinChiActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:

        dangNhap.setVisible(true);
        jPanel1.removeAll();
//        jPanel3.removeAll();
        mainView.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonHocActionPerformed
        // TODO add your handling code here:
        MonHocView MonHocView = new MonHocView();
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(MonHocView);
        jPanel1.validate();
        jPanel1.repaint();
    }//GEN-LAST:event_btnMonHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnGiangVien;
    private javax.swing.JButton btnLopTinChi;
    private javax.swing.JButton btnMonHoc;
    private javax.swing.JButton btnPhienDangKy;
    private javax.swing.JButton btnSinhVien;
    private javax.swing.JButton btnThongTinCaNhan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
