/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.NhanVienPDT;
import entity.MonHoc;
import entity.HocKy;
import dao.MonHocDAO;
import dao.HocKyDAO;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class MonHocView extends javax.swing.JPanel {

    /**
     * Creates new form MonHocView
     */
    public void fillDataTable(List<MonHoc> listmh){        
        HocKyDAO hkdao = new HocKyDAO();
        List<HocKy> listhk = hkdao.getListHocKy();
        int i = 1;
        DefaultTableModel model = (DefaultTableModel) tableMonHoc.getModel();
        model.setRowCount(0);
        for(MonHoc mh : listmh){
            Object dataRow[] = new Object[12];
            dataRow[0] = i++;
            dataRow[1] = mh.getMaMonHoc();
            dataRow[2] = mh.getTenMonhoc();
            dataRow[3] = mh.getSoTicChi();
            model.addRow(dataRow);
        }
        model.fireTableDataChanged();
    }    
    public MonHocView() {
        initComponents();
        MonHocDAO mhdao = new MonHocDAO();
        List<MonHoc> listmh = mhdao.getListMonHoc();
        fillDataTable(listmh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSoTinChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaMH = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTenMonHoc = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMonHoc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã Môn Học");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 10, 90, 40);

        txtSoTinChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoTinChi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSoTinChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoTinChiActionPerformed(evt);
            }
        });
        jPanel3.add(txtSoTinChi);
        txtSoTinChi.setBounds(110, 80, 260, 40);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Số tín chỉ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 80, 90, 40);

        txtMaMH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaMH.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMHActionPerformed(evt);
            }
        });
        jPanel3.add(txtMaMH);
        txtMaMH.setBounds(110, 10, 260, 40);

        jPanel4.setLayout(null);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tên Môn Học");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 10, 90, 40);

        txtTenMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtTenMonHoc);
        txtTenMonHoc.setBounds(100, 10, 260, 40);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 10));

        btnInsert.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsert.setText("Thêm");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel5.add(btnInsert);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel5.add(btnEdit);

        btnFind.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFind.setText("Tìm kiếm");
        btnFind.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel5.add(btnFind);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        tableMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null},
                {"2", null, null, null},
                {"3", null, null, null},
                {"4", null, null, null},
                {"5", null, null, null},
                {"6", null, null, null},
                {"7", null, null, null},
                {"8", null, null, null},
                {"9", null, null, null},
                {"10", null, null, null}
            },
            new String [] {
                "STT", "Mã Môn Học", "Tên Môn Học", "Số Tín Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMonHoc);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Môn Học");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean isValidForm(){
        if(Integer.parseInt(txtSoTinChi.getText().strip()) < 2 && Integer.parseInt(txtSoTinChi.getText().strip()) > 4){
            JOptionPane.showMessageDialog(this, "Số tín chỉ không bé hơn 2 và không lớn hơn 4!");
            return false;
        }
        return true;
    }
    public MonHoc getModel(){
        MonHoc mh = new MonHoc();
        HocKyDAO hkdao = new HocKyDAO();
        mh.setMaMonHoc(txtMaMH.getText().strip());
        mh.setTenMonhoc(txtTenMonHoc.getText().strip());
        mh.setSoTicChi(Integer.parseInt(txtSoTinChi.getText().strip()));
        return mh;
    }
    public void setModel(MonHoc mh){
        HocKyDAO hkdao = new HocKyDAO();
        txtMaMH.setText(mh.getMaMonHoc());
        txtTenMonHoc.setText(mh.getTenMonhoc());
        txtSoTinChi.setText(Integer.toString(mh.getSoTicChi()));
    }
    public void resetModel(){
        txtMaMH.setText("");
        txtTenMonHoc.setText("");
        txtSoTinChi.setText("");
    } 
    
    private void txtSoTinChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoTinChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoTinChiActionPerformed

    private void txtMaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMHActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        MonHocDAO mhdao = new MonHocDAO();
        List<MonHoc> listmh = null;
        MonHoc mh = getModel();
        try {
            if(isValidForm()){
                if(mhdao.addMonHocToDB(mh) > 0){
                    mhdao = new MonHocDAO();
                    listmh = mhdao.getListMonHoc();
                    fillDataTable(listmh);
                    JOptionPane.showMessageDialog(this, "Thêm thành công Môn học!");
                    resetModel();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm không thành công Môn học!");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        MonHocDAO mhdao = new MonHocDAO();
        List<MonHoc> listmh = null;
        MonHoc mh = getModel();

        try {
            if(isValidForm()){
                if(mhdao.editMonHocToDB(mh) > 0){
                    mhdao = new MonHocDAO();
                    listmh = mhdao.getListMonHoc();
                    fillDataTable(listmh);
                    JOptionPane.showMessageDialog(this, "Sửa thành công Môn học!");
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa không thành công Môn học!");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        MonHocDAO mhdao = new MonHocDAO();
        HocKyDAO hkdao = new HocKyDAO();
        List<MonHoc> listAllMh = mhdao.getListMonHoc();
        List<MonHoc> listFilteredMh = new ArrayList<MonHoc>();
        if(txtMaMH.getText().strip().equals("") 
                && txtTenMonHoc.getText().strip().equals("")
                && txtSoTinChi.getText().strip().equals("")
        ){
            
            JOptionPane.showMessageDialog(this, "Nhập thông tin môn học để tìm kiếm!");
        } else {
            for(MonHoc mh: listAllMh){
                if( mh.getMaMonHoc().contains(txtMaMH.getText().strip())
                && mh.getTenMonhoc().contains(txtTenMonHoc.getText().strip())
                && (txtSoTinChi.getText().strip().equals("") ? true  : mh.getSoTicChi() == Integer.parseInt(txtSoTinChi.getText().strip()))
                ){
                    listFilteredMh.add(mh);
                } 
            }
            fillDataTable(listFilteredMh);
        }        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        MonHocDAO mhdao = new MonHocDAO();
        int confirm = JOptionPane.showConfirmDialog(null,
            "Bạn có chắc chắn muốn xóa?", "Xóa!", JOptionPane.DEFAULT_OPTION);
        // 0=yes, 1=no, 2=cancel
        if(confirm == 0){
            if(mhdao.checkMonHocLopTinChiByID(txtMaMH.getText().strip()) == -1){
                JOptionPane.showMessageDialog(this, "Môn học đã có lớp tín chỉ, không thể xóa!");
            } else {
                
                if(mhdao.delMonHocByID(txtMaMH.getText().strip()) > 0){
                    JOptionPane.showMessageDialog(this, "Xóa thành công sinh viên!");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công sinh viên!");
                }              
            }

        }        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMonHocMouseClicked
        // TODO add your handling code here:
        int stt = tableMonHoc.rowAtPoint(evt.getPoint());
        String MaMH = tableMonHoc.getValueAt(stt, 1).toString();
        MonHocDAO mhdao = new MonHocDAO();
        MonHoc mh = mhdao.getMonHocByID(MaMH);
        setModel(mh);
    }//GEN-LAST:event_tableMonHocMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMonHoc;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtSoTinChi;
    private javax.swing.JTextField txtTenMonHoc;
    // End of variables declaration//GEN-END:variables
}
