/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.NhanVienPDT;

import dao.CT_HocKy_NamHoc_DAO;
import dao.GiaTinChiDAO;
import dao.HocKyDAO;
import dao.NamHocDAO;
import dao.PhienDAO;
import entity.CT_HocKy_NamHoc;
import entity.HocKy;
import entity.NamHoc;
import entity.Phien;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class NamHocPhienView extends javax.swing.JPanel {
    public void fillDataTableNHHK(List<CT_HocKy_NamHoc> listCTHKNH){
        NamHocDAO nhdao = new NamHocDAO();
        HocKyDAO hkdao = new HocKyDAO();
        GiaTinChiDAO gtcdao = new GiaTinChiDAO();
        int i = 1;
        DefaultTableModel model = (DefaultTableModel) tableNHHK.getModel();
        model.setRowCount(0);
        for(CT_HocKy_NamHoc item : listCTHKNH){
            Object dataRow[] = new Object[14];
            dataRow[0] = i++;
            dataRow[1] = nhdao.getNamHocByID(item.getMaNamHoc()).getTenNamHoc();
            dataRow[2] = hkdao.getHocKyByID(item.getMaHocKy()).getHocKy();
            dataRow[3] = item.getNgayBatDau();
            dataRow[4] = item.getNgayKetThuc();
            dataRow[5] = gtcdao.getGiaTinChiByID(item.getIdgtc()).getGiaTien() + "000 VND";
            model.addRow(dataRow);
        }
        model.fireTableDataChanged();
    }
        public void fillDataTablePhien(List<Phien> listphien){
        NamHocDAO nhdao = new NamHocDAO();
        HocKyDAO hkdao = new HocKyDAO();
        CT_HocKy_NamHoc_DAO ctnhhkdao = new CT_HocKy_NamHoc_DAO();
        int i = 1;
        DefaultTableModel model = (DefaultTableModel) tablePhien.getModel();
        model.setRowCount(0);
        for(Phien item : listphien){
            Object dataRow[] = new Object[14];
            dataRow[0] = i++;
            dataRow[1] = nhdao.getNamHocByID(ctnhhkdao.getCT_HocKy_NamHocByID(item.getId_cthknh()).getMaNamHoc()).getTenNamHoc();
            dataRow[2] = hkdao.getHocKyByID(ctnhhkdao.getCT_HocKy_NamHocByID(item.getId_cthknh()).getMaHocKy()).getHocKy();
            dataRow[3] = item.getNgayBD();
            dataRow[4] = item.getNgayKT();
            model.addRow(dataRow);
        }
        model.fireTableDataChanged();
    }
    public void fillComboBoxNamHocPhien(){
        NamHocDAO nhdao = new NamHocDAO();
        List<NamHoc> listnh = nhdao.getListNamHoc();
        comboBoxNamHocPhien.removeAllItems();
        comboBoxNamHocPhien.addItem("Năm Học");
        for(NamHoc nh : listnh){
            String elm = nh.getTenNamHoc();
            comboBoxNamHocPhien.addItem(elm);
        }
    }
    public void fillComboBoxHocKyNHHK(){
        HocKyDAO hkdao = new HocKyDAO();
        List<HocKy> listhk = hkdao.getListHocKy();
        comboBoxHocKyNHHK.removeAllItems();
        comboBoxHocKyNHHK.addItem("Học Kỳ");
        for(HocKy hk : listhk){
            String elm = hk.getHocKy();
            comboBoxHocKyNHHK.addItem(elm);
        }
    } 
    public void fillComboBoxHocKyPhien(){
        HocKyDAO hkdao = new HocKyDAO();
        List<HocKy> listhk = hkdao.getListHocKy();
        comboBoxHocKyPhien.removeAllItems();
        comboBoxHocKyPhien.addItem("Học Kỳ");
        for(HocKy hk : listhk){
            String elm = hk.getHocKy();
            comboBoxHocKyPhien.addItem(elm);
        }
    } 
    public void fillComboBoxNamHocNHHK(){
        NamHocDAO nhdao = new NamHocDAO();
        List<NamHoc> listnh = nhdao.getListNamHoc();
        comboBoxNamHocNHHK.removeAllItems();
        comboBoxNamHocNHHK.addItem("Năm Học");
        for(NamHoc nh : listnh){
            String elm = nh.getTenNamHoc();
            comboBoxNamHocNHHK.addItem(elm);
        }
    }
    /**
     * Creates new form DangKyPhienView
     */
    public NamHocPhienView() {
        initComponents();
        CT_HocKy_NamHoc_DAO cthknhdao = new CT_HocKy_NamHoc_DAO();
        PhienDAO phiendao = new PhienDAO();
        fillComboBoxHocKyNHHK();
        fillComboBoxHocKyPhien();
        fillComboBoxNamHocNHHK();
        fillComboBoxNamHocPhien();
        fillDataTableNHHK(cthknhdao.getListCT_HocKy_NamHoc());
        fillDataTablePhien(phiendao.getListPhien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNgayKetThuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayBatDau = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboBoxNamHocNHHK = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtGiaTC = new javax.swing.JTextField();
        comboBoxHocKyNHHK = new javax.swing.JComboBox<>();
        btnInsertNamHoc = new javax.swing.JButton();
        btnDelNamHoc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPanell = new javax.swing.JScrollPane();
        tableNHHK = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnInsertNHHK = new javax.swing.JButton();
        btnEditNHHK = new javax.swing.JButton();
        btnFindNHHK = new javax.swing.JButton();
        btnDeleteNHHK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNgayKetThucPhien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNgayBatDauPhien = new javax.swing.JTextField();
        comboBoxNamHocPhien = new javax.swing.JComboBox<>();
        comboBoxHocKyPhien = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablePhien = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnInsertPhien = new javax.swing.JButton();
        btnEditPhien = new javax.swing.JButton();
        btnFindPhien = new javax.swing.JButton();
        btnDeletePhien = new javax.swing.JButton();

        jPanel3.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Năm Học");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 10, 90, 40);

        txtNgayKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayKetThuc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNgayKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayKetThucActionPerformed(evt);
            }
        });
        jPanel3.add(txtNgayKetThuc);
        txtNgayKetThuc.setBounds(250, 110, 120, 40);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Học Kỳ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 60, 90, 40);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Thời hạn");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 110, 90, 40);

        txtNgayBatDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayBatDau.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNgayBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayBatDauActionPerformed(evt);
            }
        });
        jPanel3.add(txtNgayBatDau);
        txtNgayBatDau.setBounds(90, 110, 100, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("-");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(200, 110, 50, 40);

        comboBoxNamHocNHHK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxNamHocNHHK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNamHocNHHKActionPerformed(evt);
            }
        });
        jPanel3.add(comboBoxNamHocNHHK);
        comboBoxNamHocNHHK.setBounds(90, 10, 120, 40);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Giá Tin Chỉ");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 160, 80, 40);

        txtGiaTC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGiaTC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGiaTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTCActionPerformed(evt);
            }
        });
        jPanel3.add(txtGiaTC);
        txtGiaTC.setBounds(90, 160, 280, 40);

        comboBoxHocKyNHHK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxHocKyNHHK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxHocKyNHHKActionPerformed(evt);
            }
        });
        jPanel3.add(comboBoxHocKyNHHK);
        comboBoxHocKyNHHK.setBounds(90, 60, 280, 40);

        btnInsertNamHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertNamHoc.setText("Thêm");
        btnInsertNamHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertNamHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertNamHocActionPerformed(evt);
            }
        });
        jPanel3.add(btnInsertNamHoc);
        btnInsertNamHoc.setBounds(220, 10, 70, 40);

        btnDelNamHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelNamHoc.setText("Xóa");
        btnDelNamHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelNamHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelNamHocActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelNamHoc);
        btnDelNamHoc.setBounds(300, 10, 70, 40);

        jPanel4.setLayout(null);

        tableNHHK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "", null, null, null, null},
                {"2", "", null, null, null, null},
                {"3", "", null, null, null, null},
                {"4", "", null, null, null, null},
                {"5", "", null, null, null, null},
                {"6", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Năm Học", "Học Kỳ", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Giá Tín Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNHHK.setRowHeight(40);
        tableNHHK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNHHKMouseClicked(evt);
            }
        });
        jScrollPanell.setViewportView(tableNHHK);

        jPanel4.add(jScrollPanell);
        jScrollPanell.setBounds(0, 0, 390, 200);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 10));

        btnInsertNHHK.setText("Thêm");
        btnInsertNHHK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertNHHKActionPerformed(evt);
            }
        });
        jPanel5.add(btnInsertNHHK);

        btnEditNHHK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditNHHK.setText("Sửa");
        btnEditNHHK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditNHHK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNHHKActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditNHHK);

        btnFindNHHK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFindNHHK.setText("Tìm kiếm");
        btnFindNHHK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFindNHHK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindNHHKActionPerformed(evt);
            }
        });
        jPanel5.add(btnFindNHHK);

        btnDeleteNHHK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteNHHK.setText("Xóa");
        btnDeleteNHHK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteNHHK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNHHKActionPerformed(evt);
            }
        });
        jPanel5.add(btnDeleteNHHK);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Năm Học Và Học Kỳ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Phiên");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setLayout(null);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Năm Học");
        jPanel7.add(jLabel4);
        jLabel4.setBounds(0, 10, 90, 40);

        txtNgayKetThucPhien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayKetThucPhien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNgayKetThucPhien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayKetThucPhienActionPerformed(evt);
            }
        });
        jPanel7.add(txtNgayKetThucPhien);
        txtNgayKetThucPhien.setBounds(90, 160, 280, 40);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Kết Thúc Phiên");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(0, 160, 90, 40);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Học Kỳ");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(0, 60, 90, 40);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bắt Đầu Phiên");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(0, 110, 90, 40);

        txtNgayBatDauPhien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayBatDauPhien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNgayBatDauPhien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayBatDauPhienActionPerformed(evt);
            }
        });
        txtNgayBatDauPhien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNgayBatDauPhienKeyPressed(evt);
            }
        });
        jPanel7.add(txtNgayBatDauPhien);
        txtNgayBatDauPhien.setBounds(90, 110, 280, 40);

        comboBoxNamHocPhien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(comboBoxNamHocPhien);
        comboBoxNamHocPhien.setBounds(90, 10, 280, 40);

        comboBoxHocKyPhien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(comboBoxHocKyPhien);
        comboBoxHocKyPhien.setBounds(90, 60, 280, 40);

        tablePhien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null},
                {"2", null, null, null, null},
                {"3", null, null, null, null},
                {"4", null, null, null, null},
                {"5", null, null, null, null},
                {"6", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Năm Học", "Học Kỳ", "Bắt Đầu Phiên", "Kết Thúc Phiên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePhien.setRowHeight(40);
        tablePhien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhienMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablePhien);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 10));

        btnInsertPhien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertPhien.setText("Thêm");
        btnInsertPhien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertPhien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPhienActionPerformed(evt);
            }
        });
        jPanel6.add(btnInsertPhien);

        btnEditPhien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditPhien.setText("Sửa");
        btnEditPhien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditPhien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPhienActionPerformed(evt);
            }
        });
        jPanel6.add(btnEditPhien);

        btnFindPhien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFindPhien.setText("Tìm kiếm");
        btnFindPhien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFindPhien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPhienActionPerformed(evt);
            }
        });
        jPanel6.add(btnFindPhien);

        btnDeletePhien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeletePhien.setText("Xóa");
        btnDeletePhien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletePhien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePhienActionPerformed(evt);
            }
        });
        jPanel6.add(btnDeletePhien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setModelHKNH(CT_HocKy_NamHoc cthknh){
        NamHocDAO nhdao = new NamHocDAO();
        HocKyDAO hkdao = new HocKyDAO();
        GiaTinChiDAO gtcdao = new GiaTinChiDAO();
        comboBoxNamHocNHHK.setSelectedItem(nhdao.getNamHocByID(cthknh.getMaNamHoc()).getTenNamHoc());
        comboBoxHocKyNHHK.setSelectedItem(hkdao.getHocKyByID(cthknh.getMaHocKy()).getHocKy());
        txtNgayBatDau.setText(cthknh.getNgayBatDau().toString());
        txtNgayKetThuc.setText(cthknh.getNgayKetThuc().toString());
        txtGiaTC.setText(Integer.toString(gtcdao.getGiaTinChiByID(cthknh.getIdgtc()).getGiaTien()));
    }
    private void resetModelHKNH(){
        comboBoxNamHocNHHK.setSelectedIndex(0);
        comboBoxHocKyNHHK.setSelectedIndex(0);
        txtNgayBatDau.setText("");
        txtNgayKetThuc.setText("");
        txtGiaTC.setText("");
    }
    private void setModelPhien(Phien p){
        NamHocDAO nhdao = new NamHocDAO();
        HocKyDAO hkdao = new HocKyDAO();
        comboBoxNamHocPhien.setSelectedItem(nhdao.getNamHocByID(new CT_HocKy_NamHoc_DAO().getCT_HocKy_NamHocByID(p.getId_cthknh()).getMaNamHoc()).getTenNamHoc());
        comboBoxHocKyPhien.setSelectedItem(hkdao.getHocKyByID(new CT_HocKy_NamHoc_DAO().getCT_HocKy_NamHocByID(p.getId_cthknh()).getMaHocKy()).getHocKy());
        txtNgayBatDauPhien.setText(p.getNgayBD().toString());
        txtNgayKetThucPhien.setText(p.getNgayKT().toString());
    }
    private void resetModelPhien(){
        comboBoxHocKyPhien.setSelectedIndex(0);
        comboBoxNamHocPhien.setSelectedIndex(0);
        txtNgayBatDauPhien.setText("");
        txtNgayKetThucPhien.setText("");
    }
    private void txtNgayKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayKetThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayKetThucActionPerformed

    private void btnEditNHHKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNHHKActionPerformed
        // TODO add your handling code here:
         NamHocDAO nhdao = new NamHocDAO();
        HocKyDAO hkdao = new HocKyDAO();
        GiaTinChiDAO gtcdao = new GiaTinChiDAO();
        CT_HocKy_NamHoc_DAO cthknhdao = new CT_HocKy_NamHoc_DAO();
        CT_HocKy_NamHoc ctnhhk = new CT_HocKy_NamHoc();
        
        try {
            ctnhhk.setMaNamHoc(nhdao.getNamHocByName(comboBoxNamHocNHHK.getSelectedItem().toString().strip()).getMaNamHoc());
           ctnhhk.setMaHocKy(hkdao.getHocKyByName(comboBoxHocKyNHHK.getSelectedItem().toString().strip()).getMaHocKy());
           SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
           Date ngayBDNHHK = null;
           Date ngayKTNHHK = null;
           try {
               ngayBDNHHK = formatter.parse(txtNgayBatDau.getText());
               ngayKTNHHK = formatter.parse(txtNgayKetThuc.getText());
           } catch (Exception e) {
               e.printStackTrace();
           }
           ctnhhk.setNgayBatDau(ngayBDNHHK);
           ctnhhk.setNgayKetThuc(ngayKTNHHK);
           ctnhhk.setIdgtc(gtcdao.mergeGiaTinChiByGiaTien(Integer.parseInt(txtGiaTC.getText())));
           if(cthknhdao.editCT_HocKy_NamHocToDB(ctnhhk) > 0){
               fillDataTableNHHK(cthknhdao.getListCT_HocKy_NamHoc());
               JOptionPane.showMessageDialog(this, "Thêm thành công năm học!");
           } else {
               JOptionPane.showMessageDialog(this, "Thêm không thành công năm học!");
           }
           
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnEditNHHKActionPerformed

    private void btnFindNHHKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindNHHKActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnFindNHHKActionPerformed

    private void btnDeleteNHHKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNHHKActionPerformed
        // TODO add your handling code here:
        CT_HocKy_NamHoc_DAO cthknhdao = new CT_HocKy_NamHoc_DAO();
        int maCTHKNH = -1;
        try {
            maCTHKNH = cthknhdao.getCT_HocKy_NamHocByNameNH_HK(comboBoxHocKyNHHK.getSelectedItem().toString(), comboBoxNamHocNHHK.getSelectedItem().toString()).getId_cthknh();

            if(cthknhdao.checkCT_HocKy_NamHocAndLTC(maCTHKNH) > 0){
                resetModelHKNH();
               JOptionPane.showMessageDialog(this, "Không thể Học Kỳ - Năm Học Đã có Lớp Tín Chỉ!");
            } else {
                if(cthknhdao.delCT_HocKy_NamHocToDB(maCTHKNH) > 0){
                    cthknhdao = new CT_HocKy_NamHoc_DAO();
                    fillDataTableNHHK(cthknhdao.getListCT_HocKy_NamHoc());
                    resetModelHKNH();
                   JOptionPane.showMessageDialog(this, "Xóa thành công Học Kỳ - Năm Học!");
               } else {
                   JOptionPane.showMessageDialog(this, "Xóa không thành công Học Kỳ - Năm Học!");
               }                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDeleteNHHKActionPerformed

    private void txtNgayBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayBatDauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayBatDauActionPerformed

    private void btnDeletePhienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePhienActionPerformed
        // TODO add your handling code here:
        
        PhienDAO pdao = new PhienDAO();
        int maPhien = -1;
        try {
            
            int maCTHKNH = new CT_HocKy_NamHoc_DAO().getCT_HocKy_NamHocByNameNH_HK(comboBoxHocKyPhien.getSelectedItem().toString(), comboBoxNamHocPhien.getSelectedItem().toString()).getId_cthknh();
            maPhien = pdao.getPhienByCTHKNH(maCTHKNH).getMaPhien();
            if(pdao.delPhienToDB(maPhien) > 0){
                    pdao = new PhienDAO();
                    fillDataTablePhien(pdao.getListPhien());
                    resetModelPhien();
                   JOptionPane.showMessageDialog(this, "Xóa thành công Phiên đăng ký!");
               } else {
                   JOptionPane.showMessageDialog(this, "Xóa không thành công Phiên đăng ký!");
               }  
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDeletePhienActionPerformed

    private void btnFindPhienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPhienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindPhienActionPerformed

    private void btnEditPhienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPhienActionPerformed
        // TODO add your handling code here:
        NamHocDAO nhdao = new NamHocDAO();
        HocKyDAO hkdao = new HocKyDAO();
        PhienDAO pdao = new PhienDAO(); 
        Phien p = new Phien();
        try {
            p.setId_cthknh(new CT_HocKy_NamHoc_DAO().getCT_HocKy_NamHocByNameNH_HK(comboBoxHocKyPhien.getSelectedItem().toString(), comboBoxNamHocPhien.getSelectedItem().toString()).getId_cthknh());
           SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
           Date ngayBD = null;
           Date ngayKT = null;
           try {
               ngayBD = formatter.parse(txtNgayBatDauPhien.getText());
               ngayKT = formatter.parse(txtNgayKetThucPhien.getText());
           } catch (Exception e) {
               e.printStackTrace();
           }
            p.setNgayBD(ngayBD);
            p.setNgayKT(ngayKT);
            if(pdao.editPhienHocToDB(p) > 0){
               fillDataTablePhien(pdao.getListPhien());
               JOptionPane.showMessageDialog(this, "Chỉnh sửa thành công phiên đăng ký!");
           } else {
               JOptionPane.showMessageDialog(this, "Chỉnh sửa không thành công phiên đăng ký!");
           }
           
        } catch (Exception e) {
        }    
    }//GEN-LAST:event_btnEditPhienActionPerformed

    private void btnInsertPhienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPhienActionPerformed
        // TODO add your handling code here:
        NamHocDAO nhdao = new NamHocDAO();
        HocKyDAO hkdao = new HocKyDAO();
        PhienDAO pdao = new PhienDAO(); 
        Phien p = new Phien();
        try {
            p.setId_cthknh(new CT_HocKy_NamHoc_DAO().getCT_HocKy_NamHocByNameNH_HK(comboBoxHocKyPhien.getSelectedItem().toString(), comboBoxNamHocPhien.getSelectedItem().toString()).getId_cthknh());
           SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
           Date ngayBD = null;
           Date ngayKT = null;
           try {
               ngayBD = formatter.parse(txtNgayBatDauPhien.getText());
               ngayKT = formatter.parse(txtNgayKetThucPhien.getText());
           } catch (Exception e) {
               e.printStackTrace();
           }
            p.setNgayBD(ngayBD);
            p.setNgayKT(ngayKT);
            if(pdao.addPhienHocToDB(p) > 0){
               fillDataTablePhien(pdao.getListPhien());
               JOptionPane.showMessageDialog(this, "Thêm thành công phiên đăng ký!");
           } else {
               JOptionPane.showMessageDialog(this, "Thêm không thành công phiên đăng ký!");
           }
           
        } catch (Exception e) {
        }        
        
    }//GEN-LAST:event_btnInsertPhienActionPerformed

    private void txtNgayBatDauPhienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayBatDauPhienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayBatDauPhienActionPerformed

    private void txtNgayKetThucPhienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayKetThucPhienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayKetThucPhienActionPerformed

    private void txtNgayBatDauPhienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgayBatDauPhienKeyPressed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayBatDauPhienKeyPressed

    private void comboBoxNamHocNHHKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNamHocNHHKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxNamHocNHHKActionPerformed

    private void txtGiaTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTCActionPerformed

    private void comboBoxHocKyNHHKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxHocKyNHHKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxHocKyNHHKActionPerformed

    private void btnInsertNHHKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertNHHKActionPerformed
        // TODO add your handling code here:
        NamHocDAO nhdao = new NamHocDAO();
        HocKyDAO hkdao = new HocKyDAO();
        GiaTinChiDAO gtcdao = new GiaTinChiDAO();
        CT_HocKy_NamHoc_DAO cthknhdao = new CT_HocKy_NamHoc_DAO();
        CT_HocKy_NamHoc ctnhhk = new CT_HocKy_NamHoc();
        
        try {
            ctnhhk.setMaNamHoc(nhdao.getNamHocByName(comboBoxNamHocNHHK.getSelectedItem().toString().strip()).getMaNamHoc());
           ctnhhk.setMaHocKy(hkdao.getHocKyByName(comboBoxHocKyNHHK.getSelectedItem().toString().strip()).getMaHocKy());
           SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
           Date ngayBDNHHK = null;
           Date ngayKTNHHK = null;
           try {
               ngayBDNHHK = formatter.parse(txtNgayBatDau.getText());
               ngayKTNHHK = formatter.parse(txtNgayKetThuc.getText());
           } catch (Exception e) {
               e.printStackTrace();
           }
           ctnhhk.setNgayBatDau(ngayBDNHHK);
           ctnhhk.setNgayKetThuc(ngayKTNHHK);
           ctnhhk.setIdgtc(gtcdao.mergeGiaTinChiByGiaTien(Integer.parseInt(txtGiaTC.getText())));
           if(cthknhdao.addCT_HocKy_NamHocToDB(ctnhhk) > 0){
               fillDataTableNHHK(cthknhdao.getListCT_HocKy_NamHoc());
               JOptionPane.showMessageDialog(this, "Thêm thành công năm học!");
           } else {
               JOptionPane.showMessageDialog(this, "Thêm không thành công năm học!");
           }
           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnInsertNHHKActionPerformed

    private void btnInsertNamHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertNamHocActionPerformed
        // TODO add your handling code here:
        NamHocDAO nhdao = new NamHocDAO();
        String nameLastNamHoc = nhdao.getLastNamHoc().getTenNamHoc();
        int tmp = Integer.parseInt(nameLastNamHoc.split("-")[1].strip());
        String tenNamHoc = Integer.toString(tmp) + "-" + Integer.toString(tmp + 1);
        if(nhdao.addNamHocToBD(tenNamHoc) > 0){
            fillComboBoxNamHocNHHK();
            comboBoxNamHocNHHK.setSelectedItem(new NamHocDAO().getLastNamHoc().getTenNamHoc());
            comboBoxNamHocPhien.setSelectedItem(new NamHocDAO().getLastNamHoc().getTenNamHoc());
            JOptionPane.showMessageDialog(this, "Thêm thành công năm học!");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm không thành công năm học!");
        }

    }//GEN-LAST:event_btnInsertNamHocActionPerformed

    private void btnDelNamHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelNamHocActionPerformed
        // TODO add your handling code here:
        NamHocDAO nhdao = new NamHocDAO();
        if(nhdao.delNamHocByIDToBD(nhdao.getLastNamHoc().getMaNamHoc()) > 0){
            fillComboBoxNamHocNHHK();
            comboBoxNamHocNHHK.setSelectedItem(new NamHocDAO().getLastNamHoc().getTenNamHoc()); 
            comboBoxNamHocPhien.setSelectedItem(new NamHocDAO().getLastNamHoc().getTenNamHoc());
            JOptionPane.showMessageDialog(this, "Xóa thành công năm học!");

        } else {
           JOptionPane.showMessageDialog(this, "Xóa thành công năm học!"); 
        }

    }//GEN-LAST:event_btnDelNamHocActionPerformed

    private void tableNHHKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNHHKMouseClicked
        // TODO add your handling code here:
        CT_HocKy_NamHoc_DAO ctnhhkdao = new CT_HocKy_NamHoc_DAO();
        
        int stt = tableNHHK.rowAtPoint(evt.getPoint());
        int idnhhk = ctnhhkdao.getCT_HocKy_NamHocByNH_HK(new HocKyDAO().getHocKyByName(tableNHHK.getValueAt(stt, 2).toString()).getMaHocKy(), new NamHocDAO().getNamHocByName(tableNHHK.getValueAt(stt, 1).toString()).getMaNamHoc()).getId_cthknh();
//                Integer.parseInt(tableNHHK.getValueAt(stt, 1).toString());
        CT_HocKy_NamHoc_DAO cthknhdao = new CT_HocKy_NamHoc_DAO();
        CT_HocKy_NamHoc ctnhhk = cthknhdao.getCT_HocKy_NamHocByID(idnhhk);
        setModelHKNH(ctnhhk);
    }//GEN-LAST:event_tableNHHKMouseClicked

    private void tablePhienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhienMouseClicked
        // TODO add your handling code here:
        CT_HocKy_NamHoc_DAO ctnhhkdao = new CT_HocKy_NamHoc_DAO();
        PhienDAO pdao = new PhienDAO();
        Phien p = new Phien();
        int stt = tablePhien.rowAtPoint(evt.getPoint());
        int idnhhk = ctnhhkdao.getCT_HocKy_NamHocByNH_HK(new HocKyDAO().getHocKyByName(tableNHHK.getValueAt(stt, 2).toString()).getMaHocKy(), new NamHocDAO().getNamHocByName(tableNHHK.getValueAt(stt, 1).toString()).getMaNamHoc()).getId_cthknh();
        p = pdao.getPhienByCTHKNH(idnhhk);
//                Integer.parseInt(tableNHHK.getValueAt(stt, 1).toString());
        setModelPhien(p);
    }//GEN-LAST:event_tablePhienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelNamHoc;
    private javax.swing.JButton btnDeleteNHHK;
    private javax.swing.JButton btnDeletePhien;
    private javax.swing.JButton btnEditNHHK;
    private javax.swing.JButton btnEditPhien;
    private javax.swing.JButton btnFindNHHK;
    private javax.swing.JButton btnFindPhien;
    private javax.swing.JButton btnInsertNHHK;
    private javax.swing.JButton btnInsertNamHoc;
    private javax.swing.JButton btnInsertPhien;
    private javax.swing.JComboBox<String> comboBoxHocKyNHHK;
    private javax.swing.JComboBox<String> comboBoxHocKyPhien;
    private javax.swing.JComboBox<String> comboBoxNamHocNHHK;
    private javax.swing.JComboBox<String> comboBoxNamHocPhien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPanell;
    private javax.swing.JTable tableNHHK;
    private javax.swing.JTable tablePhien;
    private javax.swing.JTextField txtGiaTC;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtNgayBatDauPhien;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextField txtNgayKetThucPhien;
    // End of variables declaration//GEN-END:variables
}
