/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.NhanVienPDT;

/**
 *
 * @author PC
 */
public class NhomView extends javax.swing.JPanel {

    /**
     * Creates new form NhomView
     */
    public NhomView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtNgayKetThuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPhong = new javax.swing.JTextField();
        txtNgayBatDau = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTietBD = new javax.swing.JTextField();
        comboBoxThu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setLayout(null);

        txtNgayKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayKetThuc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNgayKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayKetThucActionPerformed(evt);
            }
        });
        jPanel3.add(txtNgayKetThuc);
        txtNgayKetThuc.setBounds(280, 70, 110, 40);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thứ trong tuần");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 130, 90, 40);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Phòng");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(200, 200, 80, 40);

        txtPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhongActionPerformed(evt);
            }
        });
        jPanel3.add(txtPhong);
        txtPhong.setBounds(290, 200, 100, 40);

        txtNgayBatDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayBatDau.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNgayBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayBatDauActionPerformed(evt);
            }
        });
        jPanel3.add(txtNgayBatDau);
        txtNgayBatDau.setBounds(110, 70, 110, 40);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thời hạn");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(0, 60, 90, 40);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Tiết bắt đầu");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(0, 210, 90, 40);

        txtTietBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTietBD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTietBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTietBDActionPerformed(evt);
            }
        });
        jPanel3.add(txtTietBD);
        txtTietBD.setBounds(110, 200, 80, 40);

        comboBoxThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(comboBoxThu);
        comboBoxThu.setBounds(110, 130, 280, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(230, 70, 37, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHÓM THỰC HÀNH");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 6, 440, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayKetThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayKetThucActionPerformed

    private void txtPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhongActionPerformed

    private void txtNgayBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayBatDauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayBatDauActionPerformed

    private void txtTietBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTietBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTietBDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxThu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtTietBD;
    // End of variables declaration//GEN-END:variables
}
