/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.SinhVien;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import sqlserver_connection.ConnectionHelper;

/**
 *
 * @author Admin
 */
public class DanhSachSinhVien extends javax.swing.JPanel {

    /**
     * Creates new form DanhSachSinhVien
     */
    public DanhSachSinhVien() {
        initComponents();
    }
    public DanhSachSinhVien(String maLTC) {
        initComponents();
        loadDSSVDK(maLTC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

public void loadDSSVDK(String maLTC) {
        MultiLineTableCellRenderer renderer = new MultiLineTableCellRenderer();
        jTable1.setDefaultRenderer(Object.class, renderer);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        ConnectionHelper connectionHelper = new ConnectionHelper();
        Connection connect = null;
        try {
            connect = connectionHelper.getConnection();
            String query = "{CALL DSSV_DK_LTC(?)}";
            CallableStatement stmt = connect.prepareCall(query);

            stmt.setString(1, maLTC);

            ResultSet result = stmt.executeQuery();

            int i = 1;

            while (result.next()) {

                Object[] obj = {
                    i++, 
                    result.getString("MaSV"), 
                    result.getString("Ho")+ " "+result.getString("TenDem")+ " "+result.getString("Ten") , 
                    result.getString("LopKhoaHoc"), 
                    result.getString("Email_1"),
                    result.getString("SoDienThoai_1"),
                };
                model.addRow(obj);

            }
            stmt.close();
            connect.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        model.fireTableDataChanged();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
