package views.SinhVien;

import dao.TaiKhoanDAO;
import entity.SinhVien;
import entity.TaiKhoan;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import sqlserver_connection.ConnectionHelper;
import views.DangNhap;

/**
 *
 * @author Admin
 */
public class DoiMatKhau extends javax.swing.JPanel {

    /**
     * Creates new form DoiMatKhau
     */
    private static DangNhap dangNhap;

    public DoiMatKhau(DangNhap dangNhap) {
        this.dangNhap = dangNhap;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        pwMKHT = new javax.swing.JPasswordField();
        pwMKM = new javax.swing.JPasswordField();
        pwMKXN = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(812, 628));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Mật khẩu hiện tại:");

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Mật khẩu mới:");

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Xác nhận:");

        btnSave.setBackground(new java.awt.Color(0, 255, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 102, 204));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        pwMKHT.setPreferredSize(new java.awt.Dimension(64, 30));

        pwMKM.setPreferredSize(new java.awt.Dimension(64, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwMKHT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwMKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwMKXN, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pwMKHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwMKM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwMKXN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnSave)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validMatKhau(String matKhau) {
        Pattern p = Pattern.compile("[\\w]{4}$");
        Matcher m = p.matcher(matKhau);
        if (m.find()) {
            return true;
        }
        return false;
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (validMatKhau(pwMKM.getText().strip()) == false) {
            JOptionPane.showMessageDialog(null, "Mat khau co do dai it nhat 4 ki tu");
            return;
        }
        if(pwMKM.getText().strip().equals(pwMKXN.getText().strip()) ==false){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng mật khẩu xác thực");       
            return;
        }
        
        String tkForm = dangNhap.getTaiKhoan();
        String mkHTForm = pwMKHT.getText().strip();
        String mkM = pwMKM.getText().strip();
        String mkXN = pwMKXN.getText().strip();
        boolean success = new TaiKhoanDAO().updateMatKhau(mkHTForm, tkForm, mkXN);
        if(success)
            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
        else
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng mật khẩu");
        
        
        
//        TaiKhoanDAO tkdao = new TaiKhoanDAO();
//        TaiKhoan taiKhoan = tkdao.getTaiKhoanByMa(dangNhap.getTaiKhoan());
//        System.out.println(taiKhoan.getTenTaiKhoan() + " " + taiKhoan.getMatKhau());
//
//        if (taiKhoan.getMatKhau().equals(pwMKHT.getText().strip())
//                && pwMKM.getText().strip().equals(pwMKXN.getText().strip())) {
//              
//            tkdao.updateMatKhau(pwMKM.getText().strip(), dangNhap.getTaiKhoan());
//            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
//        }
//        else if( taiKhoan.getMatKhau().equals(pwMKHT.getText().strip()) == false){
//            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng mật khẩu");
//        }
//        else if(pwMKM.getText().strip().equals(pwMKXN.getText().strip()) ==false){
//            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng mật khẩu xác thực");            
//        }
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pwMKHT;
    private javax.swing.JPasswordField pwMKM;
    private javax.swing.JPasswordField pwMKXN;
    // End of variables declaration//GEN-END:variables
}
