package views.SinhVien;

import views.*;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import sqlserver_connection.ConnectionHelper;

public class HomeSinhVien extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form HomeSinhVien
     */
    private static DangNhap dangNhap;
    private static MainView mainView;

//    private static ThongTinCaNhan thongTinCaNhan;
//    private  SuaThongTinCaNhanSV suaThongTinCaNhanSV;
//    private   DangKyMonHoc dangKyMonHoc;
//    private  DanhSachMonDK danhSachMonDK = new DanhSachMonDK();
    public HomeSinhVien(DangNhap dangNhap, MainView mainView) {

        initComponents();
        this.dangNhap = dangNhap;
        this.mainView = mainView;

//        thongTinCaNhan = new ThongTinCaNhan(dangNhap);
//        suaThongTinCaNhanSV = new SuaThongTinCaNhanSV(dangNhap);
        btnThongTin.addActionListener(this);
        btnDangKy.addActionListener(this);
        btnSuaThongTin.addActionListener(this);
        btnXemDS.addActionListener(this);
        btnXemLichHoc.addActionListener(this);
        btnMatKhau.addActionListener(this);
        btnLogOut.addActionListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelNoiDung = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnThongTin = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        btnXemDS = new javax.swing.JButton();
        btnSuaThongTin = new javax.swing.JButton();
        btnMatKhau = new javax.swing.JButton();
        btnXemLichHoc = new javax.swing.JButton();
        txtGioiThieu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();

        jpanelNoiDung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanelNoiDung.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThongTin.setBackground(new java.awt.Color(204, 255, 255));
        btnThongTin.setForeground(new java.awt.Color(204, 255, 255));
        btnThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sv.png"))); // NOI18N

        btnDangKy.setBackground(new java.awt.Color(0, 204, 255));
        btnDangKy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(0, 0, 153));
        btnDangKy.setText("Đăng ký");

        btnXemDS.setBackground(new java.awt.Color(0, 204, 255));
        btnXemDS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXemDS.setForeground(new java.awt.Color(0, 0, 153));
        btnXemDS.setText("Xem Danh Sach Lớp");
        btnXemDS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSuaThongTin.setBackground(new java.awt.Color(0, 204, 255));
        btnSuaThongTin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSuaThongTin.setForeground(new java.awt.Color(0, 0, 153));
        btnSuaThongTin.setText("Sửa Thông Tin");

        btnMatKhau.setBackground(new java.awt.Color(0, 204, 255));
        btnMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMatKhau.setForeground(new java.awt.Color(0, 0, 153));
        btnMatKhau.setText("Đổi mật khẩu");

        btnXemLichHoc.setBackground(new java.awt.Color(0, 204, 255));
        btnXemLichHoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXemLichHoc.setForeground(new java.awt.Color(0, 0, 153));
        btnXemLichHoc.setText("Xem Lịch Học");
        btnXemLichHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLichHocActionPerformed(evt);
            }
        });

        txtGioiThieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGioiThieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.jpg"))); // NOI18N
        jLabel1.setText("Học viện Công nghệ BTVT TPHCM");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jLabel1.setPreferredSize(new java.awt.Dimension(265, 77));
        jLabel1.setRequestFocusEnabled(false);

        btnLogOut.setBackground(new java.awt.Color(0, 204, 255));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(0, 0, 153));
        btnLogOut.setText("Log out");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXemLichHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXemDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGioiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXemDS)
                .addGap(18, 18, 18)
                .addComponent(btnSuaThongTin)
                .addGap(18, 18, 18)
                .addComponent(btnXemLichHoc)
                .addGap(18, 18, 18)
                .addComponent(btnMatKhau)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemLichHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLichHocActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnXemLichHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMatKhau;
    private javax.swing.JButton btnSuaThongTin;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btnXemDS;
    private javax.swing.JButton btnXemLichHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpanelNoiDung;
    private javax.swing.JLabel txtGioiThieu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(btnDangKy)) {
            btnDangKyClick();
        } else if (e.getSource().equals(btnXemDS)) {
            btnXemDSClick();
        } else if (e.getSource().equals(btnThongTin)) {
            btnTTCaNhanClick();
        } else if (e.getSource().equals(btnSuaThongTin)) {
            btnSuaThongTinClick();
        } else if (e.getSource().equals(btnMatKhau)) {
            btnMatKhauClick();
        } else if (e.getSource().equals(btnXemLichHoc)) {
            btnXemLichHoc();
        } else if (e.getSource().equals(btnLogOut)) {
            btnLogOut();
        }
    }

    public void setPanel(JPanel c) {
        jpanelNoiDung.removeAll();
        jpanelNoiDung.setLayout(new BorderLayout());
        jpanelNoiDung.add(c);
        jpanelNoiDung.validate();
        jpanelNoiDung.repaint();
    }

    public void btnTTCaNhanClick() {
        setPanel(new ThongTinCaNhan(dangNhap));
    }

    public void btnDangKyClick() {
        setPanel(new DangKyLTC(dangNhap));
    }

    public void btnXemDSClick() {
        setPanel(new DanhSachLopDK(dangNhap));
    }

    public void btnSuaThongTinClick() {
        setPanel(new SuaThongTinCaNhanSV(dangNhap));
    }

    public void btnMatKhauClick() {
        setPanel(new DoiMatKhau(dangNhap));
    }

    public void btnXemLichHoc() {
        setPanel(new XemLichHoc(dangNhap, this));
    }

    public void btnLogOut() {

        dangNhap.setVisible(true);
        jpanelNoiDung.removeAll();
        mainView.dispose();

    }

    public void setContent() {

        ConnectionHelper connectionHelper = new ConnectionHelper();
        Connection connect = null;
        connect = connectionHelper.getConnection();
        String SQL = String.format("SELECT Ho, TenDem, Ten FROM SinhVien WHERE MaSV = '%s'", dangNhap.getTaiKhoan());
        try {

            Statement stmt = connect.createStatement();
            ResultSet result = stmt.executeQuery(SQL);

            if (result.next()) {
                String ho = result.getString("Ho");
                String tenDem = result.getString("TenDem");
                String ten = result.getString("Ten");
                txtGioiThieu.setText(ho + " " + tenDem + " " + ten);

            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
