package views;

import java.sql.PreparedStatement;

import com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement;
import controller.DangNhapController;
import dao.ChucVuDAO;
import dao.TaiKhoanDAO;
import entity.ChucVu;
import java.util.List;
import java.awt.BorderLayout;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import views.SinhVien.HomeSinhVien;
import entity.TaiKhoan;
import javax.swing.JOptionPane;
import views.NhanVienPDT.HomeNhanVien;

public class DangNhap extends javax.swing.JFrame {

    private static MainView mview = new MainView();
    private static HomeSinhVien homeSinhVien;
    private static HomeNhanVien homeNhanVien;

    private String taiKhoan;

    /**
     * Creates new form FormDangNhap
     */
    public DangNhap() {
        homeSinhVien = new HomeSinhVien(this, mview);
        homeNhanVien = new HomeNhanVien(this, mview);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Đăng Nhập");

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tài Khoản");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mật Khẩu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDangNhap)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(txtTaiKhoan))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDangNhap)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean CheckLogin(String tkFormValue, String mkFormValue, String rsTaiKhoan, String rsMatKhau) {
        return tkFormValue.equalsIgnoreCase(rsTaiKhoan) && mkFormValue.equalsIgnoreCase(rsMatKhau);
    }

    public void setTaiKhoan(String taiKhoanIn) {
        this.taiKhoan = taiKhoanIn;
    }

    public String getTaiKhoan() {
        return this.taiKhoan;
    }


    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        TaiKhoanDAO tkDAO = new TaiKhoanDAO();

        String tkFormValue = txtTaiKhoan.getText().strip();
        String mkFormValue = txtMatKhau.getText().strip();
//        TaiKhoan tk = tkDAO.getTaiKhoanByMa(tkFormValue);
        String taiKhoan = tkDAO.getTaiKhoanByMa(tkFormValue, mkFormValue);
        if (taiKhoan.equalsIgnoreCase("") == false) {
            if (taiKhoan.equalsIgnoreCase("SV")) {

                setTaiKhoan(tkFormValue);
//                    System.out.println(taiKhoan);
                mview.setDefaultCloseOperation(EXIT_ON_CLOSE);
                mview.setLocationRelativeTo(null);
                mview.getContentPane().removeAll();
                mview.setLayout(new BorderLayout());
                mview.getContentPane().add(homeSinhVien);
                mview.revalidate();
                mview.repaint();
                homeSinhVien.setContent();
                
                mview.setVisible(true);

                this.dispose();
            } else {
                setTaiKhoan(tkFormValue);
                mview.setDefaultCloseOperation(EXIT_ON_CLOSE);
                mview.setLocationRelativeTo(null);
                mview.getContentPane().removeAll();
                mview.setLayout(new BorderLayout());
                mview.getContentPane().add(homeNhanVien);
                mview.revalidate();
                mview.repaint();
                mview.setVisible(true);
                this.dispose();
            }
        } else {

            JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu không chính xác");
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                formDangNhap.setLocationRelativeTo(null);
//                formDangNhap.setDefaultCloseOperation(EXIT_ON_CLOSE);
//                formDangNhap.setVisible(true);
//                
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
